# Generated by Django 5.1.5 on 2026-07-19 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_orders', models.BooleanField(default=False, verbose_name='دسترسی به سفارشات')),
                ('access_customers', models.BooleanField(default=False, verbose_name='دسترسی به مشتریان')),
                ('access_products', models.BooleanField(default=False, verbose_name='دسترسی به محصولات')),
                ('access_warehouse', models.BooleanField(default=False, verbose_name='دسترسی به انبار')),
                ('access_production', models.BooleanField(default=False, verbose_name='دسترسی به تولید')),
                ('access_reports', models.BooleanField(default=False, verbose_name='دسترسی به گزارشات')),
                ('is_admin_user', models.BooleanField(default=False, verbose_name='مدیریت کاربران (ادمین)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
