# Generated by Django 5.1.5 on 2026-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(default='کارخانجات نساجی حاما پارچه', max_length=200, verbose_name='نام کارخانه')),
                ('phone', models.CharField(default='021-12345678', max_length=50, verbose_name='تلفن تماس')),
                ('address', models.TextField(default='تهران، شهرک صنعتی، بلوار صنعت، خیابان نساجی، پلاک ۱۰', verbose_name='آدرس کارخانه')),
                ('national_id', models.CharField(default='10100001234', max_length=50, verbose_name='کد اقتصادی / شناسه ملی')),
                ('currency', models.CharField(default='تومان', max_length=50, verbose_name='واحد پولی پیش\u200cفرض')),
                ('vat_rate', models.IntegerField(default=10, verbose_name='نرخ مالیات بر ارزش افزوده (%)')),
                ('length_unit', models.CharField(default='متر', max_length=50, verbose_name='واحد طول پارچه پیش\u200cفرض')),
                ('sepidar_sync', models.BooleanField(default=True, verbose_name='فعال بودن اتصال به سپیدار')),
                ('sepidar_api_url', models.CharField(default='https://api.sepidar.hama.ir/v1', max_length=255, verbose_name='آدرس وب\u200cسرویس سپیدار')),
                ('auto_deduct_stock', models.BooleanField(default=True, verbose_name='کسر خودکار موجودی انبار هنگام پایان تولید')),
            ],
            options={
                'verbose_name': 'تنظیمات عمومی',
                'verbose_name_plural': 'تنظیمات عمومی',
            },
        ),
    ]
