# Generated by Django 5.1.5 on 2026-07-19 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام انبار')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد انبار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('warehouse_type', models.CharField(choices=[('raw_material', 'مواد اولیه'), ('finished_goods', 'محصول نهایی'), ('semi_finished', 'نیمه\u200cساخته'), ('other', 'سایر')], default='raw_material', max_length=50, verbose_name='نوع انبار')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'ورودی'), ('OUT', 'خروجی')], max_length=3, verbose_name='نوع تراکنش')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار')),
                ('unit', models.CharField(default='عدد', max_length=20, verbose_name='واحد اندازه\u200cگیری (متر/عدد/کیلو/بسته)')),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام تأمین\u200cکننده')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('consumption_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مقدار مصرف')),
                ('transaction_category', models.CharField(choices=[('foreign_purchase', 'خرید خارجی'), ('domestic_purchase', 'خرید داخلی'), ('production', 'تولید'), ('return', 'مرجوعی'), ('other', 'سایر')], default='other', max_length=50, verbose_name='نوع تراکنش (خرید/تولید/...)')),
                ('order_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مانده سفارش')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='مرجع (سفارش/تولید/رسید)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='کالا')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'تراکنش انبار',
                'verbose_name_plural': 'تراکنش\u200cهای انبار',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='موجودی فعلی')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='حداقل موجودی')),
                ('max_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حداکثر موجودی')),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='نقطه سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='کالا')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'موجودی کالا',
                'verbose_name_plural': 'موجودی کالاها',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
