# Generated by Django 5.1.5 on 2026-07-19 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=50, unique=True, verbose_name='کد ماشین')),
                ('name', models.CharField(max_length=100, verbose_name='نام ماشین')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('repair', 'در حال تعمیر'), ('inactive', 'غیرفعال')], default='active', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ماشین',
                'verbose_name_plural': 'ماشین\u200cآلات',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_code', models.CharField(max_length=50, unique=True, verbose_name='کد اپراتور')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('leave', 'مرخصی'), ('inactive', 'غیرفعال')], default='active', max_length=20, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'اپراتور',
                'verbose_name_plural': 'اپراتورها',
            },
        ),
        migrations.CreateModel(
            name='WorkStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد مرحله')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله کاری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مرحله کاری',
                'verbose_name_plural': 'مراحل کاری',
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_code', models.CharField(max_length=50, unique=True, verbose_name='کد برنامه\u200cریزی')),
                ('target_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار هدف تولید')),
                ('produced_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار تولید شده واقعی')),
                ('raw_material_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار مواد اولیه مصرفی')),
                ('material_deducted', models.BooleanField(default=False, verbose_name='آیا مواد اولیه کسر شده است؟')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار شروع'), ('producing', 'در حال تولید'), ('completed', 'تکمیل شده'), ('suspended', 'متوقف شده')], default='pending', max_length=20, verbose_name='وضعیت برنامه\u200cریزی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.machine', verbose_name='ماشین')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.operator', verbose_name='اپراتور')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='سفارش مرتبط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='products.product', verbose_name='محصول تولیدی')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_raw_materials', to='products.product', verbose_name='مواد اولیه مصرفی')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='انبار مبدا مواد اولیه')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.workstage', verbose_name='مرحله تولید')),
            ],
            options={
                'verbose_name': 'برنامه\u200cریزی تولید',
                'verbose_name_plural': 'برنامه\u200cریزی\u200cهای تولید',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
