# Generated by Django 5.1.5 on 2026-07-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='stoppage_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت توقف'),
        ),
    ]
