# Generated by Django 5.1.5 on 2026-07-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_planning_stoppage_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_code', models.CharField(max_length=50, unique=True, verbose_name='شماره / کد درخواست نت')),
                ('date', models.DateField(verbose_name='تاریخ اعلام درخواست')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='محل استقرار')),
                ('has_stoppage', models.BooleanField(default=False, verbose_name='توقف خط تولید (دارد/ندارد)')),
                ('notification_time', models.TimeField(verbose_name='ساعت اعلام درخواست')),
                ('deadline_date', models.DateField(verbose_name='مهلت انجام')),
                ('estimated_days', models.PositiveIntegerField(default=1, verbose_name='زمان تقریبی (روز)')),
                ('requester_unit', models.CharField(choices=[('machining', 'واحد ماشینکاری'), ('weaving', 'واحد بافندگی'), ('spinning', 'واحد ریسندگی'), ('cutting', 'واحد برشکاری'), ('sewing', 'واحد دوخت'), ('dyeing', 'واحد رنگرزی'), ('finishing', 'واحد تکمیل'), ('other', 'سایر واحدها')], default='machining', max_length=50, verbose_name='واحد درخواست\u200cکننده')),
                ('repair_type', models.CharField(choices=[('emergency', 'تعمیر اضطراری (EM)'), ('preventive', 'نگهداری پیشگیرانه (PM)'), ('periodic', 'سرویس دوره\u200cای'), ('overhaul', 'اورهال / بازسازی'), ('other', 'سایر موارد')], default='emergency', max_length=30, verbose_name='نوع تعمیر')),
                ('failure_electrical', models.BooleanField(default=False, verbose_name='خرابی برقی')),
                ('failure_mechanical', models.BooleanField(default=False, verbose_name='خرابی مکانیکی')),
                ('failure_hydraulic', models.BooleanField(default=False, verbose_name='خرابی هیدرولیک')),
                ('failure_utilities', models.BooleanField(default=False, verbose_name='خرابی تاسیساتی')),
                ('failure_other', models.BooleanField(default=False, verbose_name='سایر موارد خرابی')),
                ('execution_group', models.CharField(default='واحد تعمیرات و نگهداری (نت)', max_length=100, verbose_name='گروه اجرایی تعمیر')),
                ('internal_repair_possible', models.BooleanField(default=True, verbose_name='امکان رفع عیب داخل شرکت')),
                ('external_repair_reason', models.TextField(blank=True, null=True, verbose_name='علت عدم امکان رفع در شرکت')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع تعمیر')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع تعمیر')),
                ('activity_description', models.TextField(blank=True, null=True, verbose_name='شرح کامل فعالیت')),
                ('consumables_used', models.TextField(blank=True, null=True, verbose_name='قطعات مصرفی مورد نیاز')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تعمیر')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان تعمیر')),
                ('total_stoppage_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='مجموع ساعت توقف')),
                ('next_checkup_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بازدید دوره\u200cای بعدی')),
                ('next_checkup_time', models.TimeField(blank=True, null=True, verbose_name='ساعت بازدید دوره\u200cای بعدی')),
                ('manager_approved', models.BooleanField(default=False, verbose_name='تایید مسئول نت')),
                ('requester_approved', models.BooleanField(default=False, verbose_name='تایید درخواست\u200cکننده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='production.machine', verbose_name='دستگاه')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.operator', verbose_name='اپراتور')),
            ],
            options={
                'verbose_name': 'درخواست نت (نگهداری و تعمیرات)',
                'verbose_name_plural': 'درخواست\u200cهای نت (نگهداری و تعمیرات)',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
