# Generated by Django 5.1.5 on 2026-07-19 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20, unique=True, verbose_name='کد سفارش')),
                ('status', models.CharField(choices=[('registered', 'ثبت شده'), ('cutting', 'برش'), ('sewing', 'دوخت'), ('quality', 'کنترل کیفیت'), ('warehouse', 'انبار'), ('delivered', 'تحویل داده شد'), ('cancelled', 'لغو شده')], default='registered', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='وزن (KG)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='طول (CM)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='عرض (CM)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='محصول')),
            ],
        ),
    ]
