# Generated by Django 5.1.5 on 2026-07-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sepidar_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد سپیدار'),
        ),
    ]
