# Generated by Django 5.1.5 on 2026-07-19 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='گروه کالا')),
            ],
            options={
                'verbose_name': 'گروه کالا',
                'verbose_name_plural': 'گروه\u200cهای کالا',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=200, verbose_name='شرح کالا')),
                ('unit', models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('بسته', 'بسته')], max_length=50, verbose_name='واحد سنجش')),
                ('initial_stock', models.PositiveIntegerField(default=0, verbose_name='موجودی اولیه')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر جاری')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productgroup', verbose_name='گروه کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
    ]
